name: CyArangoDB Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "21"
          cache: maven
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

      - name: Compile
        run: mvn --batch-mode compile

      - name: Install
        run: mvn --batch-mode install

      - name: Run tests
        run: mvn -B test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: target/CyArangoDB*.jar
